export enum ToastEventNames {
  mount = 'mount',
  unmount = 'unmount',
  add = 'add',
  update = 'update',
  remove = 'remove',
  removed = 'removed',
  setExiting = 'setExiting',
  setEntering = 'setEntering',
  setShowing = 'setShowing',
  transitShowing = 'transitShowing',
  transitEntering = 'transitEntering',
  transitExiting = 'transitExiting',
  continueEnteringTransition = 'continueEnteringTransition',
  continueExitingTransition = 'continueExitingTransition',
  continueShowingTransition = 'continueShowingTransition',
  stopEnteringTransition = 'stopEnteringTransition',
  stopExitingTransition = 'stopExitingTransition',
  stopShowingTransition = 'stopShowingTransition',
}
